version: '3.8'

services:
  postgres:
    container_name: postgres_db_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres.tchkarrwxtjmbmpkabqt
      POSTGRES_PASSWORD: Visual.ai1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    networks:
      - visual-ai-network

networks:
  visual-ai-network:
    driver: bridge
